{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-broker-svc" (include "kafka.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker
spec:
  clusterIP: None
  selector: 
    {{- include "kafka.selectorLabels" . | nindent 4}}
    app.kubernetes.io/component: broker
  ports:
  - name: internal
    port: {{ .Values.kafka.broker.ports.internal }}
  - name: kraft
    port: {{ .Values.kafka.broker.ports.kraft }}
  - name: controller
    port: {{ .Values.kafka.broker.ports.controller }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "kafka.name" .) }}
  labels: 
    {{- include "kafka.labels" . | nindent 4}}
spec:
  type: ClusterIP
  clusterIP: None
  selector: 
    {{- include "kafka.selectorLabels" . | nindent 4}}
{{- end }}
