apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-master-svc" (include "spark.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "spark.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  clusterIP: None
  selector: 
    {{- include "spark.selectorLabels" . | nindent 4}}
    app.kubernetes.io/component: master
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: spark
    protocol: TCP
    port: 7077
    targetPort: 7077
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "spark.name" .) }}
  labels: 
    {{- include "spark.labels" . | nindent 4}}
spec:
  type: ClusterIP
  clusterIP: None
  selector: 
    {{- include "spark.selectorLabels" . | nindent 4}}
