{{- if .Values.spark.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-master-svc" (include "spark.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "spark.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  type: {{ .Values.spark.service.type }}
  {{- if and .Values.spark.service.clusterIP (eq .Values.spark.service.type "ClusterIP") }}
  clusterIP: {{ .Values.spark.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.spark.service.type "LoadBalancer") (not (empty .Values.spark.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.spark.service.loadBalancerIP }}
  {{- end }}
  selector: 
    {{- include "spark.selectorLabels" . | nindent 4}}
    app.kubernetes.io/component: master
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.spark.service.ports.http }}
    targetPort: http
    {{- if and .Values.spark.service.nodePorts.http (or (eq .Values.spark.service.type "NodePort") (eq .Values.spark.service.type "LoadBalancer")) }}
    nodePort: {{ .Values.spark.service.nodePorts.http }}
    {{- end}}

  - name: protocol
    protocol: TCP
    port: {{ .Values.spark.service.ports.protocol }}
    targetPort: protocol
    {{- if and .Values.spark.service.nodePorts.protocol (or (eq .Values.spark.service.type "NodePort") (eq .Values.spark.service.type "LoadBalancer")) }}
    nodePort: {{ .Values.spark.service.nodePorts.protocol }}
    {{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "spark.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "spark.labels" . | nindent 4}}
spec:
  type: ClusterIP
  clusterIP: None
  selector: 
    {{- include "spark.selectorLabels" . | nindent 4}}
{{- end }}
