{{- if .Values.hdfs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configmap" (include "hdfs.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hdfs.labels" . | nindent 4 }}
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
    <property>
        <name>fs.default.name</name>
        <value>{{ printf "hdfs://%s-namenode-svc" (include "hdfs.name" .) }}</value> 
    </property>
    <property>
        <name>fs.defaultFS</name>
        <value>{{ printf "hdfs://%s-namenode-svc:%d" (include "hdfs.name" .) (int .Values.hdfs.service.ports.protocol) }}</value> 
    </property>
    </configuration>
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
    <property>
        <name>dfs.namenode.rpc-bind-host</name>
        <value>0.0.0.0</value>
    </property>

    <property>
        <name>dfs.namenode.http-bind-host</name>
        <value>0.0.0.0</value>
    </property>

    <property>
        <name>dfs.namenode.rpc-address</name>
        <value>{{ printf "%s-namenode-svc:%d" (include "hdfs.name" .) (int .Values.hdfs.service.ports.protocol) }}</value>
    </property>

    <property>
        <name>dfs.namenode.http-address</name>
        <value>{{ printf "%s-namenode-svc:%d" (include "hdfs.name" .) (int .Values.hdfs.service.ports.http) }}</value>
    </property>

    <property>
        <name>dfs.replication</name>
        <value>{{ .Values.hdfs.replication }}</value>
    </property>

    <property>
        <name>dfs.namenode.name.dir</name>
        <value>{{ .Values.hdfs.namenode.dir }}</value>
    </property>

    <property>
        <name>dfs.datanode.data.dir</name>
        <value>{{ .Values.hdfs.datanode.dir }}</value>
    </property>
    
    </configuration>
{{- end }}
