{{- if .Values.hdfs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-namenode-svc" (include "hdfs.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "hdfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: namenode
spec:
  clusterIP: None
  selector: 
    {{- include "hdfs.selectorLabels" . | nindent 4}}
    app.kubernetes.io/component: namenode
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.hdfs.namenode.ports.http }}
    targetPort: http
  - name: protocol
    protocol: TCP
    port: {{ .Values.hdfs.namenode.ports.protocol }}
    targetPort: protocol
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "hdfs.name" .) }}
  labels: 
    {{- include "hdfs.labels" . | nindent 4}}
spec:
  type: ClusterIP
  clusterIP: None
  selector: 
    {{- include "hdfs.selectorLabels" . | nindent 4}}
{{- end }}
