apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-namenode-svc" (include "hdfs.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "hdfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: namenode
spec:
  clusterIP: None
  selector: 
    {{- include "hdfs.selectorLabels" . | nindent 4}}
    app.kubernetes.io/component: namenode
  ports:
  - protocol: TCP
    name: http
    port: 9870
    targetPort: 9870
  - protocol: TCP
    name: hdfs
    port: 8020
    targetPort: 8020
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "hdfs.name" .) }}
  labels: 
    {{- include "hdfs.labels" . | nindent 4}}
spec:
  type: ClusterIP
  clusterIP: None
  selector: 
    {{- include "hdfs.selectorLabels" . | nindent 4}}
