apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_ENABLE_KRAFT: "yes"
  KAFKA_CFG_PROCESS_ROLES: "broker,controller"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "kraft:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT"
  ALLOW_ANONYMOUS_LOGIN: "yes"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  BITNAMI_DEBUG: "yes"
  KAFKA_CFG_KRAFT_REPLICATION_FACTOR: "1"
  KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_KRAFT_CLUSTER_ID: "Bf-r4F4DSmSMQd8ax5lTHg"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
