apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  selector:
    app: kafka-broker
  clusterIP: None
  ports:
  - name: internal
    port: 9092
  - name: kraft
    port: 9093
  - name: controller
    port: 9094
