affinity:
  enabled: false

hdfs:
  enabled: true
  name: "hdfs"
  image:
    registry: docker.io
    repository: apache/hadoop
    tag: 3.3.6
    pullPolicy: IfNotPresent

  replication: 1

  service:
    type: ClusterIP
    clusterIP: None

  namenode:
    mountPath: "/hadoop/dfs/namenode"
    resources: {"requests": {"cpu": "0.5", "memory": "1024Mi"}, "limits": {"cpu": "1.0", "memory": "1024Mi"}}
    persistence:
      size: 2G

    containerPorts:
      http: 9870
      protocol: 8020

    ports:
      http: 9870
      protocol: 8020

    nodePorts:
      http: ""
      protocol: ""

  datanode:
    hostname: ""
    mountPath: "/hadoop/dfs/datanode"
    replicas: 1

    resources: {"requests": {"cpu": "0.5", "memory": "1024Mi"}, "limits": {"cpu": "1.0", "memory": "1024Mi"}}
    persistence:
      size: 10G

    containerPorts:
      http: 9864

    ports:
      http: 9864

    nodePorts:
      http: ""

spark:
  enabled: true
  name: "spark"
  image:
    registry: docker.io
    repository: vmsou/dnids-spark
    tag: 3.5.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    clusterIP: None

  master:
    daemonMemoryLimit: ""

    resources: {"requests": {"cpu": "0.5", "memory": "1024Mi"}, "limits": {"cpu": "1.0", "memory": "1024Mi"}}

    containerPorts:
      webui: 8080
      protocol: 7077
    
    ports:
      webui: 8080
      protocol: 7077

    nodePorts:
      webui: ""
      protocol: ""

    loadBalancerIP: ""

  worker:
    replicas: 1
    daemonMemoryLimit: ""
    memoryLimit: ""

    resources: {"requests": {"cpu": "0.5", "memory": "1024Mi"}, "limits": {"cpu": "1.0", "memory": "1024Mi"}}

    containerPorts:
      webui: 8081
      driverui: 4040

    ports:
      webui: 8081
      driverui: 4040

    nodePorts:
      webui: ""
      driverui: ""

    loadBalancerIP: ""

kafka:
  enabled: true
  name: "kafka"
  image:
    registry: docker.io
    repository: bitnami/kafka
    tag: 3.6.2
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    clusterIP: None

    ports:
      internal: 9092
      kraft: 9093
      controller: 9094

    nodePorts:
      internal: ""
      kraft: ""
      controller: ""

  broker:
    replicas: 1

    BITNAMI_DEBUG: "yes"
    ALLOW_ANONYMOUS_LOGIN: "yes"
    KRAFT_REPLICATION_FACTOR: "1"
    DEFAULT_REPLICATION_FACTOR: "1"

    resources: {"requests": {"cpu": "0.5", "memory": "1024Mi"}, "limits": {"cpu": "1.0", "memory": "1024Mi"}}
    persistence:
      size: 5G

    containerPorts:
      internal: 9092
      kraft: 9093
      controller: 9094

# Default
magePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
