
affinity:
  enabled: false

hdfs:
  enabled: true
  name: "hdfs"
  image:
    repository: apache/hadoop
    tag: 3.3.6
    pullPolicy: IfNotPresent

  replication: 1

  service:
    type: ClusterIP
    clusterIP: None

    ports:
      http: 9870
      protocol: 8020

    nodePorts:
      http: ""
      protocol: ""

  namenode:
    mountPath: "/hadoop/dfs/namenode"
    resources: {"requests": {"cpu": "0.5", "memory": "1024Mi"}, "limits": {"cpu": "1", "memory": "2048Mi"}}
    persistence:
      size: 2G

    containerPorts:
      http: 9870
      protocol: 8020

  datanode:
    mountPath: "/hadoop/dfs/datanode"
    replicas: 1

    resources: {"requests": {"cpu": "0.5", "memory": "512Mi"}, "limits": {"cpu": "1", "memory": "1024Mi"}}
    persistence:
      size: 10G

spark:
  enabled: true
  name: "spark"
  image:
    repository: vmsou/dnids-spark
    tag: 3.5.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    clusterIP: None

    ports:
      http: 8080
      protocol: 7077

    nodePorts:
      http: ""
      protocol: ""

    loadBalancerIP: ""

  master:
    daemonMemoryLimit: ""

    #resources: {"requests": {"cpu": "0.5", "memory": "512Mi", "ephemeral-storage": "50Mi"}, "limits": {"cpu": "1.0", "memory": "3072Mi", "ephemeral-storage": "2Gi"}}
    resources: {"requests": {"cpu": "0.5", "memory": "512Mi"}, "limits": {"cpu": "1.0", "memory": "3072Mi"}}

    containerPorts:
      http: 8080
      protocol: 7077

  worker:
    replicas: 1
    daemonMemoryLimit: ""
    memoryLimit: ""

    # resources: {"requests": {"cpu": "1.0", "memory": "2048Mi"}, "limits": {"cpu": "2.0", "memory": "3072Mi"}}
    # resources: {"requests": {"cpu": "1.0", "memory": "3072Mi", "ephemeral-storage": "50Mi"}, "limits": {"cpu": "4.0", "memory": "12288Mi", "ephemeral-storage": "16Gi"}}
    resources: {"requests": {"cpu": "1.0", "memory": "3072Mi"}, "limits": {"cpu": "4.0", "memory": "12288Mi"}}

    containerPorts:
      http: 8080

kafka:
  enabled: true
  name: "kafka"
  image:
    repository: bitnami/kafka
    tag: 3.6.2
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    clusterIP: None

    ports:
      internal: 9092
      kraft: 9093
      controller: 9094

    nodePorts:
      internal: ""
      kraft: ""
      controller: ""

  broker:
    replicas: 1

    BITNAMI_DEBUG: "yes"
    ALLOW_ANONYMOUS_LOGIN: "yes"
    KRAFT_REPLICATION_FACTOR: "1"
    DEFAULT_REPLICATION_FACTOR: "1"

    resources: {"requests": {"cpu": "0.5", "memory": "512Mi"}, "limits": {"cpu": "1.0", "memory": "2024Mi"}}
    persistence:
      size: 2G

    containerPorts:
      internal: 9092
      kraft: 9093
      controller: 9094

# Default
magePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

