apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-configmap
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
                <name>fs.default.name</name>
                <value>hdfs://hdfs-namenode</value>
        </property>
        <property>
                <name>fs.defaultFS</name>
                <value>hdfs://hdfs-namenode:8020</value>
        </property>
    </configuration>
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
                <name>dfs.namenode.rpc-address</name>
                <value>hdfs-namenode:8020</value>
        </property>
        <property>
                <name>dfs.replication</name>
                <value>1</value>
        </property>
        <property>
                <name>dfs.namenode.name.dir</name>
                <value>file:///opt/hadoop/hdfs/namenode</value>
        </property>
        <property>
                <name>dfs.datanode.data.dir</name>
                <value>file:///opt/hadoop/hdfs/datanode</value>
        </property>
    </configuration>