apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
spec:
  selector:
    app: hdfs-namenode
  clusterIP: None
  ports:
    - protocol: TCP
      name: hdfs-namenode-ui
      port: 9870
      targetPort: 9870
    - protocol: TCP
      name: hdfs-namenode-protocol
      port: 8020
      targetPort: 8020
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
spec:
  selector:
    app: hdfs-datanode
  clusterIP: None
  ports:
    - protocol: TCP
      name: hdfs-datanode-protocol
      port: 8081
      targetPort: 8081
