apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode-svc
  labels:
    app: hdfs
    role: namenode
spec:
  selector:
    app: hdfs
    role: namenode
  clusterIP: None
  ports:
    - protocol: TCP
      name: http
      port: 9870
      targetPort: 9870
    - protocol: TCP
      name: hdfs
      port: 8020
      targetPort: 8020
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-headless
  labels:
    app: hdfs
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hdfs
