apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs
    role: namenode
spec:
  selector:
    matchLabels:
      app: hdfs
      role: namenode
  serviceName: hdfs-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: hdfs
        role: namenode
    spec:
      volumes:
        - name: hdfs-configmap
          configMap:
            name: hdfs-configmap
      initContainers:
        - name: init-chown
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /hadoop/dfs/namenode && chmod -R 755 /hadoop/dfs/namenode']
          volumeMounts:
            - name: hdfs-namenode-data
              mountPath: /hadoop/dfs/namenode
      containers:
      - image: apache/hadoop:3.3.6
        name: hdfs-namenode
        resources:
           requests:
            memory: "512Mi"
            cpu: "500m"
           limits:
            memory: "768Mi"
            cpu: "750m"

        volumeMounts:
          - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            name: hdfs-configmap
            subPath: core-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            name: hdfs-configmap
            subPath: hdfs-site.xml
          - mountPath: /hadoop/dfs/namenode
            name: hdfs-namenode-data
            
        command: ["/bin/sh"]
        args: ["-c", "if [ ! -f /hadoop/dfs/namenode/current/VERSION ]; then hdfs namenode -format -force; fi && exec hdfs namenode"]

  volumeClaimTemplates:
  - metadata:
      name: hdfs-namenode-data
    spec:
      storageClassName: hdfs-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs
    role: datanode
spec:
  selector:
    matchLabels:
      app: hdfs
      role: datanode
  serviceName: hdfs-headless
  replicas: 2
  template:
    metadata:
      labels:
        app: hdfs
        role: datanode
    spec:
      volumes:
        - name: hdfs-configmap
          configMap:
            name: hdfs-configmap
      initContainers:
        - name: init-chown
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /hadoop/dfs/datanode && chmod -R 755 /hadoop/dfs/datanode']
          volumeMounts:
            - name: hdfs-datanode-data
              mountPath: /hadoop/dfs/datanode
      containers:
      - image: apache/hadoop:3.3.6
        name: hdfs-datanode
        resources:
           requests:
            memory: "512Mi"
            cpu: "500m"
           limits:
            memory: "768Mi"
            cpu: "750m"

        volumeMounts:
          - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            name: hdfs-configmap
            subPath: core-site.xml
          - mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            name: hdfs-configmap
            subPath: hdfs-site.xml
          - mountPath: /hadoop/dfs/datanode
            name: hdfs-datanode-data
            
        command: ["hdfs", "datanode"]

  volumeClaimTemplates:
  - metadata:
      name: hdfs-datanode-data
    spec:
      storageClassName: hdfs-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
