apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  labels:
    app: spark
    role: master
spec:
  selector:
    app: spark
    role: master
  clusterIP: None
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: spark
      port: 7077
      targetPort: 7077
---
apiVersion: v1
kind: Service
metadata:
  name: spark-headless
  labels:
    app: spark
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: spark
