apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master # has to match .spec.template.metadata.labels
  serviceName: "spark-master"
  replicas: 1 # by default is 1
  podManagementPolicy: Parallel
  minReadySeconds: 120 # by default is 0
  template:
    metadata:
      labels:
        app: spark-master # has to match .spec.selector.matchLabels
    spec:
      volumes:
        - name: spark-configmap
          configMap:
            name: spark-configmap
      terminationGracePeriodSeconds: 120
      containers:
      - image: bitnami/spark:3.5.1
        name: spark-master
        env:
        - name: SPARK_MODE
          value: master
        resources:
           requests:
            memory: "512Mi"
            cpu: "500m"
           limits:
            memory: "768Mi"
            cpu: "750m"
        volumeMounts:
          - mountPath: /opt/bitnami/spark/conf/spark-defaults.conf
            name: spark-configmap
            subPath: spark-defaults.conf
          - mountPath: /opt/bitnami/spark/conf/log4j2.properties
            name: spark-configmap
            subPath: log4j2.properties
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
spec:
  selector:
    matchLabels:
      app: spark-worker # has to match .spec.template.metadata.labels
  serviceName: "spark-worker"
  replicas: 2 # by default is 1
  podManagementPolicy: Parallel
  minReadySeconds: 120 # by default is 0
  template:
    metadata:
      labels:
        app: spark-worker # has to match .spec.selector.matchLabels
    spec:
      volumes:
        - name: spark-configmap
          configMap:
            name: spark-configmap
      terminationGracePeriodSeconds: 120
      containers:
      - image: bitnami/spark:3.5.1
        name: spark-worker
        env:
        - name: SPARK_MODE
          value: worker
        resources:
           requests:
            memory: "512Mi"
            cpu: "500m"
           limits:
            memory: "768Mi"
            cpu: "750m"
        volumeMounts:
          - mountPath: /opt/bitnami/spark/conf/spark-defaults.conf
            name: spark-configmap
            subPath: spark-defaults.conf
          - mountPath: /opt/bitnami/spark/conf/log4j2.properties
            name: spark-configmap
            subPath: log4j2.properties
