apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
  labels:
    app: spark
    role: master
spec:
  selector:
    matchLabels:
      app: spark
      role: master
  serviceName: spark-headless
  replicas: 1 # by default is 1
  podManagementPolicy: Parallel
  minReadySeconds: 120 # by default is 0
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      volumes:
        - name: spark-configmap
          configMap:
            name: spark-configmap
      terminationGracePeriodSeconds: 30
      containers:
      - image: vmsou/dnids-spark:3.5.1
        name: spark-master
        env:
        - name: SPARK_MODE
          value: master
        resources:
           requests:
            memory: "512Mi"
            cpu: "500m"
           limits:
            memory: "768Mi"
            cpu: "750m"
        volumeMounts:
          - mountPath: /opt/bitnami/spark/conf/spark-defaults.conf
            name: spark-configmap
            subPath: spark-defaults.conf
          - mountPath: /opt/bitnami/spark/conf/log4j2.properties
            name: spark-configmap
            subPath: log4j2.properties
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  selector:
    matchLabels:
      app: spark
      role: worker
  serviceName: spark-headless
  replicas: 2 # by default is 1
  podManagementPolicy: Parallel
  minReadySeconds: 120 # by default is 0
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      volumes:
        - name: spark-configmap
          configMap:
            name: spark-configmap
      terminationGracePeriodSeconds: 30
      containers:
      - image: vmsou/dnids-spark:3.5.1
        name: spark-worker
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_WORKER_MEMORY
          value: "2g"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master-svc:7077"
        resources:
           requests:
            memory: "512Mi"
            cpu: "500m"
           limits:
            memory: "2Gi"
            cpu: "2"
        volumeMounts:
          - mountPath: /opt/bitnami/spark/conf/spark-defaults.conf
            name: spark-configmap
            subPath: spark-defaults.conf
          - mountPath: /opt/bitnami/spark/conf/log4j2.properties
            name: spark-configmap
            subPath: log4j2.properties
